# Generated by Django 5.2.5 on 2025-08-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[('REGISTRATION_OTP', 'REGISTRATION_OTP'), ('REGISTRATION_CONFIRMATION', 'REGISTRATION_CONFIRMATION'), ('PASSWORD_CHANGE', 'PASSWORD_CHANGE'), ('PROFILE_UPDATE', 'PROFILE_UPDATE')], max_length=50)),
                ('template', models.TextField()),
            ],
        ),
    ]
