# Generated by Django 5.2.5 on 2025-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='Email Subject', max_length=100),
        ),
    ]
