# Generated by Django 5.2.5 on 2025-08-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_emailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='identifier',
            field=models.CharField(choices=[('REGISTRATION_OTP', 'REGISTRATION_OTP'), ('REGISTRATION_CONFIRMATION', 'REGISTRATION_CONFIRMATION'), ('RESET_PASSWORD', 'RESET_PASSWORD'), ('RESET_PASSWORD_OTP', 'RESET_PASSWORD_OTP'), ('PROFILE_UPDATE', 'PROFILE_UPDATE')], max_length=50),
        ),
    ]
