# Generated by Django 5.2.5 on 2025-08-21 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/products/')),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('yellow', 'Yellow')], default='white', max_length=30)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('home & kitchen', 'Home & Kitchen'), ('beauty & personal car', 'Beauty & Personal Care'), ('books', 'Books'), ('toys', 'Toys'), ('sports', 'Sports'), ('clothing', 'Clothing')], default='', max_length=40)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
